
CREATE TABLE IF NOT EXISTS "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS "items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "is_available" boolean NOT NULL,
  "owner_id" int,
  "request_id" int
);

CREATE TABLE IF NOT EXISTS "requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar,
  "requestor_id" int
);

CREATE TABLE IF NOT EXISTS "bookings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "start_date" timestamp CHECK ( start_date > current_timestamp ),
  "end_date" timestamp CHECK ( end_date > start_date ),
  "item_id" int,
  "booker_id" int,
  "status" varchar
);

CREATE TABLE IF NOT EXISTS "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "text" varchar NOT NULL CHECK ( text != '' ),
  "item_id" int,
  "author_id" int,
  "created" timestamp CHECK ( created < current_timestamp )
);

ALTER TABLE "items" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "items" ADD FOREIGN KEY ("request_id") REFERENCES "requests" ("id");

ALTER TABLE "requests" ADD FOREIGN KEY ("requestor_id") REFERENCES "users" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("item_id") REFERENCES "items" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("booker_id") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("item_id") REFERENCES "items" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id");
